apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }
spec:
  ingressClassName: public
  rules:
  - host: argocd.sandman01.k8s.local
    http:
      paths:
      #- backend:
      #    service:
      #      name: argocd-server
      #      port:
      #        name: http
      #  path: /api/dex/callback
      #  pathType: Prefix
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix